---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt::default]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]
  - name: centos-6.5
    run_list:
      - recipe[yum-epel::default]
  - name: centos-5.10
    run_list:
      - recipe[yum-epel::default]

suites:
  - name: default
    run_list:
      - recipe[zeromq-cookbook::default]
    attributes:
      zeromq:
        install_dir: "/usr/local"
  - name: specific_version
    run_list:
      - recipe[zeromq-cookbook::default]
    attributes:
      zeromq:
        src_version: "3.2.4"
        src_checksum: "df96a141c85b65c2cb6c0db22223126623a09eecbfccb7f74400f3f938742f59"
        install_dir: "/usr/local"

